have_fun: false
language: Korean
locale: ko-KR
output_language: Korean

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  language: Korean
  locale: ko-KR
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: true
    language: Korean

reviews:
  language: Korean

settings:
  language: Korean
  locale: ko-KR

ignore_patterns: []
